package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * AuthorJournals generated by hbm2java
 */
public class AuthorJournals implements java.io.Serializable {

	private AuthorJournalsId id;

	public AuthorJournals() {
	}

	public AuthorJournals(AuthorJournalsId id) {
		this.id = id;
	}

	public AuthorJournalsId getId() {
		return this.id;
	}

	public void setId(AuthorJournalsId id) {
		this.id = id;
	}

}
