package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * AuthorBooks generated by hbm2java
 */
public class AuthorBooks implements java.io.Serializable {

	private AuthorBooksId id;

	public AuthorBooks() {
	}

	public AuthorBooks(AuthorBooksId id) {
		this.id = id;
	}

	public AuthorBooksId getId() {
		return this.id;
	}

	public void setId(AuthorBooksId id) {
		this.id = id;
	}

}
