package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * AuthorConf generated by hbm2java
 */
public class AuthorConf implements java.io.Serializable {

	private AuthorConfId id;

	public AuthorConf() {
	}

	public AuthorConf(AuthorConfId id) {
		this.id = id;
	}

	public AuthorConfId getId() {
		return this.id;
	}

	public void setId(AuthorConfId id) {
		this.id = id;
	}

}
