package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Books generated by hbm2java
 */
public class Books implements java.io.Serializable {

	private int resourceId;
	private String isbn;
	private String title;
	private int yearPublished;
	private String type;
	private String publisher;
	private String edition;
	private int copies;
	private String hostLib;
	private Set<ReservedBooks> reservedBookses = new HashSet<ReservedBooks>(0);
	private String author;

	public String getAuthor() {
		return this.author;
	}


	public void setAuthor(String author) {
		this.author = author;
	}


	public Books() {
	}

	
	public Books(Resources resources, String isbn, String title,
			int yearPublished, String type, String publisher,
			String edition, int copies, String hostLib,
			Set<ReservedBooks> reservedBookses) {
		
		this.isbn = isbn;
		this.title = title;
		this.yearPublished = yearPublished;
		this.type = type;
		this.publisher = publisher;
		this.edition = edition;
		this.copies = copies;
		this.hostLib = hostLib;
		this.reservedBookses = reservedBookses;
	}

	public int getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(int resourceId) {
		this.resourceId = resourceId;
	}

	
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getYearPublished() {
		return this.yearPublished;
	}

	public void setYearPublished(int yearPublished) {
		this.yearPublished = yearPublished;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public String getEdition() {
		return this.edition;
	}

	public void setEdition(String edition) {
		this.edition = edition;
	}

	public int getCopies() {
		return this.copies;
	}

	public void setCopies(int copies) {
		this.copies = copies;
	}

	public String getHostLib() {
		return this.hostLib;
	}

	public void setHostLib(String hostLib) {
		this.hostLib = hostLib;
	}

	public Set<ReservedBooks> getReservedBookses() {
		return this.reservedBookses;
	}

	public void setReservedBookses(Set<ReservedBooks> reservedBookses) {
		this.reservedBookses = reservedBookses;
	}

}
