package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * CamerasId generated by hbm2java
 */
public class CamerasId implements java.io.Serializable {

	private String cameraId;
	private BigDecimal resId;

	public CamerasId() {
	}

	public CamerasId(String cameraId, BigDecimal resId) {
		this.cameraId = cameraId;
		this.resId = resId;
	}

	public String getCameraId() {
		return this.cameraId;
	}

	public void setCameraId(String cameraId) {
		this.cameraId = cameraId;
	}

	public BigDecimal getResId() {
		return this.resId;
	}

	public void setResId(BigDecimal resId) {
		this.resId = resId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CamerasId))
			return false;
		CamerasId castOther = (CamerasId) other;

		return ((this.getCameraId() == castOther.getCameraId()) || (this
				.getCameraId() != null && castOther.getCameraId() != null && this
				.getCameraId().equals(castOther.getCameraId())))
				&& ((this.getResId() == castOther.getResId()) || (this
						.getResId() != null && castOther.getResId() != null && this
						.getResId().equals(castOther.getResId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCameraId() == null ? 0 : this.getCameraId().hashCode());
		result = 37 * result
				+ (getResId() == null ? 0 : this.getResId().hashCode());
		return result;
	}

}
