package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ConferenceProceedings generated by hbm2java
 */
public class ConferenceProceedings implements java.io.Serializable {

	private String conf_num;
	private int resource_id;
	private String title;
	private int yearPublished;
	private String conferenceName;
	private String hostLibrary;
	private String author;


	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public ConferenceProceedings() {
	}

	public ConferenceProceedings(String conf_num, int resource_id) {
		this.conf_num = conf_num;
		this.resource_id = resource_id;
	}

	public ConferenceProceedings(String conf_num,
			int resource_id, String title, int yearPublished,
			String conferenceName, String hostLibrary) {
		this.conf_num = conf_num;
		this.resource_id = resource_id;
		this.title = title;
		this.yearPublished = yearPublished;
		this.conferenceName = conferenceName;
		this.hostLibrary = hostLibrary;
	}

	public String getConfNum() {
		return this.conf_num;
	}

	public void setConfNum(String conf_num) {
		this.conf_num = conf_num;
	}

	

	public int getResource_id() {
		return resource_id;
	}

	public void setResource_id(int resource_id) {
		this.resource_id = resource_id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getYearPublished() {
		return this.yearPublished;
	}

	public void setYearPublished(int yearPublished) {
		this.yearPublished = yearPublished;
	}

	public String getConferenceName() {
		return this.conferenceName;
	}

	public void setConferenceName(String conferenceName) {
		this.conferenceName = conferenceName;
	}

	public String getHostLibrary() {
		return this.hostLibrary;
	}

	public void setHostLibrary(String hostLibrary) {
		this.hostLibrary = hostLibrary;
	}

}
