package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Courses generated by hbm2java
 */
public class Courses implements java.io.Serializable {

	private int cid;
	private Faculty faculty;
	private String cname;
	private Teaches teaches;
	private Set<ReservedBooks> reservedBookses = new HashSet<ReservedBooks>(0);

	public Courses() {
	}

	public Courses(int cid) {
		this.cid = cid;
	}

	public Courses(int cid, Faculty faculty, String cname,
			Teaches teaches, Set<ReservedBooks> reservedBookses) {
		this.cid = cid;
		this.faculty = faculty;
		this.cname = cname;
		this.teaches = teaches;
		this.reservedBookses = reservedBookses;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public Faculty getFaculty() {
		return this.faculty;
	}

	public void setFaculty(Faculty faculty) {
		this.faculty = faculty;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public Teaches getTeaches() {
		return this.teaches;
	}

	public void setTeaches(Teaches teaches) {
		this.teaches = teaches;
	}

	public Set<ReservedBooks> getReservedBookses() {
		return this.reservedBookses;
	}

	public void setReservedBookses(Set<ReservedBooks> reservedBookses) {
		this.reservedBookses = reservedBookses;
	}

}
