package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * Databasechangelog generated by hbm2java
 */
public class Databasechangelog implements java.io.Serializable {

	private DatabasechangelogId id;

	public Databasechangelog() {
	}

	public Databasechangelog(DatabasechangelogId id) {
		this.id = id;
	}

	public DatabasechangelogId getId() {
		return this.id;
	}

	public void setId(DatabasechangelogId id) {
		this.id = id;
	}

}
