package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1



/**
 * Faculty generated by hbm2java
 */
public class Faculty implements java.io.Serializable {

	private String facUnityid;
	private String category;
	private String facultyNumber;
	
	public Faculty() {
	}


	public Faculty(String facUnityid, String category, String facultyNumber) {
		
		this.category = category;
		this.facultyNumber = facultyNumber;
		this.facUnityid = facUnityid;
	}

	public String getFacUnityid() {
		return this.facUnityid;
	}

	public void setFacUnityid(String facUnityid) {
		this.facUnityid = facUnityid;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getFacultyNumber() {
		return this.facultyNumber;
	}

	public void setFacultyNumber(String facultyNumber) {
		this.facultyNumber = facultyNumber;
	}

}