package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * History generated by hbm2java
 */
public class History implements java.io.Serializable {

	private HistoryId id;
	private Date dueDate;
	private Set<RentalHistory> rentalHistories = new HashSet<RentalHistory>(0);

	public History() {
	}

	public History(HistoryId id, Date dueDate) {
		this.id = id;
		this.dueDate = dueDate;
	}

	public History(HistoryId id, Date dueDate,
			Set<RentalHistory> rentalHistories) {
		this.id = id;
		this.dueDate = dueDate;
		this.rentalHistories = rentalHistories;
	}

	public HistoryId getId() {
		return this.id;
	}

	public void setId(HistoryId id) {
		this.id = id;
	}

	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	public Set<RentalHistory> getRentalHistories() {
		return this.rentalHistories;
	}

	public void setRentalHistories(Set<RentalHistory> rentalHistories) {
		this.rentalHistories = rentalHistories;
	}

}
