package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * HistoryId generated by hbm2java
 */
public class HistoryId implements java.io.Serializable {

	private Date checkedIn;
	private Date checkedOut;

	public HistoryId() {
	}

	public HistoryId(Date checkedIn, Date checkedOut) {
		this.checkedIn = checkedIn;
		this.checkedOut = checkedOut;
	}

	public Date getCheckedIn() {
		return this.checkedIn;
	}

	public void setCheckedIn(Date checkedIn) {
		this.checkedIn = checkedIn;
	}

	public Date getCheckedOut() {
		return this.checkedOut;
	}

	public void setCheckedOut(Date checkedOut) {
		this.checkedOut = checkedOut;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HistoryId))
			return false;
		HistoryId castOther = (HistoryId) other;

		return ((this.getCheckedIn() == castOther.getCheckedIn()) || (this
				.getCheckedIn() != null && castOther.getCheckedIn() != null && this
				.getCheckedIn().equals(castOther.getCheckedIn())))
				&& ((this.getCheckedOut() == castOther.getCheckedOut()) || (this
						.getCheckedOut() != null
						&& castOther.getCheckedOut() != null && this
						.getCheckedOut().equals(castOther.getCheckedOut())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCheckedIn() == null ? 0 : this.getCheckedIn().hashCode());
		result = 37
				* result
				+ (getCheckedOut() == null ? 0 : this.getCheckedOut()
						.hashCode());
		return result;
	}

}
