package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * JournalsId generated by hbm2java
 */
public class JournalsId implements java.io.Serializable {

	private String issn;
	private BigDecimal resourceId;

	public JournalsId() {
	}

	public JournalsId(String issn, BigDecimal resourceId) {
		this.issn = issn;
		this.resourceId = resourceId;
	}

	public String getIssn() {
		return this.issn;
	}

	public void setIssn(String issn) {
		this.issn = issn;
	}

	public BigDecimal getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(BigDecimal resourceId) {
		this.resourceId = resourceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JournalsId))
			return false;
		JournalsId castOther = (JournalsId) other;

		return ((this.getIssn() == castOther.getIssn()) || (this.getIssn() != null
				&& castOther.getIssn() != null && this.getIssn().equals(
				castOther.getIssn())))
				&& ((this.getResourceId() == castOther.getResourceId()) || (this
						.getResourceId() != null
						&& castOther.getResourceId() != null && this
						.getResourceId().equals(castOther.getResourceId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIssn() == null ? 0 : this.getIssn().hashCode());
		result = 37
				* result
				+ (getResourceId() == null ? 0 : this.getResourceId()
						.hashCode());
		return result;
	}

}
