package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Journals generated by hbm2java
 */
@SuppressWarnings("serial")
public class Journals implements java.io.Serializable {

	private String issn;
	private int resource_id;
	private String title;
	private int yearPublished;
	private String hostLibrary;
	private String author;

	public String getAuthor() {
		return this.author;
	}



	public void setAuthor(String author) {
		this.author = author;
	}



	public Journals() {
	}

	

	public Journals(String issn, int resources, String title,
			int yearPublished, String hostLibrary, String author) {
		this.issn = issn;
		this.resource_id = resources;
		this.title = title;
		this.yearPublished = yearPublished;
		this.hostLibrary = hostLibrary;
		this.author = author;
	}



	public String getIssn() {
		return issn;
	}



	public void setIssn(String issn) {
		this.issn = issn;
	}



	

	public int getResource_id() {
		return resource_id;
	}



	public void setResource_id(int resource_id) {
		this.resource_id = resource_id;
	}



	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getYearPublished() {
		return this.yearPublished;
	}

	public void setYearPublished(int yearPublished) {
		this.yearPublished = yearPublished;
	}

	public String getHostLibrary() {
		return this.hostLibrary;
	}

	public void setHostLibrary(String hostLibrary) {
		this.hostLibrary = hostLibrary;
	}

}
