package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Patrons generated by hbm2java
 */
public class Patrons implements java.io.Serializable {

	private String unityid;
	private String password;
	private String firstname;
	private String lastname;
	private String dept;
	private String nationality;
	private String sex;
	private Faculty faculty;
	private Students students;
	private Set<RentalHistory> rentalHistories = new HashSet<RentalHistory>(0);

	public Patrons() {
	}

	public Patrons(String unityid) {
		this.unityid = unityid;
	}

	public Patrons(String unityid, String password, String firstname,
			String lastname, String dept, String nationality, String sex,
			Faculty faculty, Students students,
			Set<RentalHistory> rentalHistories) {
		this.unityid = unityid;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.dept = dept;
		this.nationality = nationality;
		this.sex = sex;
		this.faculty = faculty;
		this.students = students;
		this.rentalHistories = rentalHistories;
	}

	public String getUnityid() {
		return this.unityid;
	}

	public void setUnityid(String unityid) {
		this.unityid = unityid;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getDept() {
		return this.dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Faculty getFaculty() {
		return this.faculty;
	}

	public void setFaculty(Faculty faculty) {
		this.faculty = faculty;
	}

	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	public Set<RentalHistory> getRentalHistories() {
		return this.rentalHistories;
	}

	public void setRentalHistories(Set<RentalHistory> rentalHistories) {
		this.rentalHistories = rentalHistories;
	}

}
