package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * RentalHistoryId generated by hbm2java
 */
public class RentalHistoryId implements java.io.Serializable {

	private String unityid;
	private BigDecimal resourceId;
	private Date checkedOut;
	private Date checkedIn;

	public RentalHistoryId() {
	}

	public RentalHistoryId(String unityid, BigDecimal resourceId,
			Date checkedOut, Date checkedIn) {
		this.unityid = unityid;
		this.resourceId = resourceId;
		this.checkedOut = checkedOut;
		this.checkedIn = checkedIn;
	}

	public String getUnityid() {
		return this.unityid;
	}

	public void setUnityid(String unityid) {
		this.unityid = unityid;
	}

	public BigDecimal getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(BigDecimal resourceId) {
		this.resourceId = resourceId;
	}

	public Date getCheckedOut() {
		return this.checkedOut;
	}

	public void setCheckedOut(Date checkedOut) {
		this.checkedOut = checkedOut;
	}

	public Date getCheckedIn() {
		return this.checkedIn;
	}

	public void setCheckedIn(Date checkedIn) {
		this.checkedIn = checkedIn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RentalHistoryId))
			return false;
		RentalHistoryId castOther = (RentalHistoryId) other;

		return ((this.getUnityid() == castOther.getUnityid()) || (this
				.getUnityid() != null && castOther.getUnityid() != null && this
				.getUnityid().equals(castOther.getUnityid())))
				&& ((this.getResourceId() == castOther.getResourceId()) || (this
						.getResourceId() != null
						&& castOther.getResourceId() != null && this
						.getResourceId().equals(castOther.getResourceId())))
				&& ((this.getCheckedOut() == castOther.getCheckedOut()) || (this
						.getCheckedOut() != null
						&& castOther.getCheckedOut() != null && this
						.getCheckedOut().equals(castOther.getCheckedOut())))
				&& ((this.getCheckedIn() == castOther.getCheckedIn()) || (this
						.getCheckedIn() != null
						&& castOther.getCheckedIn() != null && this
						.getCheckedIn().equals(castOther.getCheckedIn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUnityid() == null ? 0 : this.getUnityid().hashCode());
		result = 37
				* result
				+ (getResourceId() == null ? 0 : this.getResourceId()
						.hashCode());
		result = 37
				* result
				+ (getCheckedOut() == null ? 0 : this.getCheckedOut()
						.hashCode());
		result = 37 * result
				+ (getCheckedIn() == null ? 0 : this.getCheckedIn().hashCode());
		return result;
	}

}
