package edu.ncsu.csc540.model;

import java.util.Date;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * RentalHistory generated by hbm2java
 */
public class RentalHistory implements java.io.Serializable {

	private int resource_id;
	private Date checked_out;
	private Date checked_in;
	private Date due_date;
	private Patrons patrons;

	public RentalHistory() {
	}

	public RentalHistory(int resource_id, Date checked_out, Date checked_in, Date due_date, Patrons patrons) {
		
		this.resource_id = resource_id;
		this.checked_out = checked_out;
		this.checked_in = checked_in;
		this.due_date = due_date;
		this.patrons = patrons;
	}

	public Date getChecked_out() {
		return checked_out;
	}

	public void setChecked_out(Date checked_out) {
		this.checked_out = checked_out;
	}

	public Date getChecked_in() {
		return checked_in;
	}

	public void setChecked_in(Date checked_in) {
		this.checked_in = checked_in;
	}

	public int getResource_id() {
		return resource_id;
	}

	public void setResource_id(int resource_id) {
		this.resource_id = resource_id;
	}

	public Patrons getPatrons() {
		return this.patrons;
	}

	public void setPatrons(Patrons patrons) {
		this.patrons = patrons;
	}

	public Date getDue_date() {
		return due_date;
	}

	public void setDue_date(Date due_date) {
		this.due_date = due_date;
	}

}
