package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReservedBooks generated by hbm2java
 */
public class ReservedBooks implements java.io.Serializable {

	private int resource_id;
	private String fac_unityid;
	private int reservedDuration;
	private int cid;
	private String ISBN;

	public ReservedBooks() {
	}

	public ReservedBooks(int resource_id, String fac_unityid,
			int reservedDuration, int cid, String ISBN) {
		this.resource_id = resource_id;
		this.fac_unityid = fac_unityid;
		this.reservedDuration = reservedDuration;
		this.cid = cid;
		this.ISBN = ISBN;
	}

	public int getResource_id() {
		return resource_id;
	}

	public void setResource_id(int resource_id) {
		this.resource_id = resource_id;
	}

	public String getFac_unityid() {
		return fac_unityid;
	}

	public void setFac_unityid(String fac_unityid) {
		this.fac_unityid = fac_unityid;
	}

	public int getReservedDuration() {
		return reservedDuration;
	}

	public void setReservedDuration(int reservedDuration) {
		this.reservedDuration = reservedDuration;
	}

	public int getCid() {
		return cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public String getISBN() {
		return ISBN;
	}

	public void setISBN(String iSBN) {
		ISBN = iSBN;
	}

	
}
