package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ReservedBooksId generated by hbm2java
 */
public class ReservedBooksId implements java.io.Serializable {

	private BigDecimal resourceId;
	private BigDecimal cid;
	private String facUnityid;
	private BigDecimal reservedDurationId;

	public ReservedBooksId() {
	}

	public ReservedBooksId(BigDecimal resourceId, BigDecimal cid,
			String facUnityid, BigDecimal reservedDurationId) {
		this.resourceId = resourceId;
		this.cid = cid;
		this.facUnityid = facUnityid;
		this.reservedDurationId = reservedDurationId;
	}

	public BigDecimal getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(BigDecimal resourceId) {
		this.resourceId = resourceId;
	}

	public BigDecimal getCid() {
		return this.cid;
	}

	public void setCid(BigDecimal cid) {
		this.cid = cid;
	}

	public String getFacUnityid() {
		return this.facUnityid;
	}

	public void setFacUnityid(String facUnityid) {
		this.facUnityid = facUnityid;
	}

	public BigDecimal getReservedDurationId() {
		return this.reservedDurationId;
	}

	public void setReservedDurationId(BigDecimal reservedDurationId) {
		this.reservedDurationId = reservedDurationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReservedBooksId))
			return false;
		ReservedBooksId castOther = (ReservedBooksId) other;

		return ((this.getResourceId() == castOther.getResourceId()) || (this
				.getResourceId() != null && castOther.getResourceId() != null && this
				.getResourceId().equals(castOther.getResourceId())))
				&& ((this.getCid() == castOther.getCid()) || (this.getCid() != null
						&& castOther.getCid() != null && this.getCid().equals(
						castOther.getCid())))
				&& ((this.getFacUnityid() == castOther.getFacUnityid()) || (this
						.getFacUnityid() != null
						&& castOther.getFacUnityid() != null && this
						.getFacUnityid().equals(castOther.getFacUnityid())))
				&& ((this.getReservedDurationId() == castOther
						.getReservedDurationId()) || (this
						.getReservedDurationId() != null
						&& castOther.getReservedDurationId() != null && this
						.getReservedDurationId().equals(
								castOther.getReservedDurationId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getResourceId() == null ? 0 : this.getResourceId()
						.hashCode());
		result = 37 * result
				+ (getCid() == null ? 0 : this.getCid().hashCode());
		result = 37
				* result
				+ (getFacUnityid() == null ? 0 : this.getFacUnityid()
						.hashCode());
		result = 37
				* result
				+ (getReservedDurationId() == null ? 0 : this
						.getReservedDurationId().hashCode());
		return result;
	}

}
