package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1



/**
 * Rooms generated by hbm2java
 */
public class Rooms implements java.io.Serializable {

	private String room_number;
	private int res_id;
	private int capacity;
	private int floor;
	private String type;

	public Rooms() {
	}

	public Rooms(String id, int resources) {
		this.room_number = id;
		this.res_id = resources;
	}

	public Rooms(String id, int resources, int capacity,
			int floor, String type) {
		this.room_number = id;
		this.res_id = resources;
		this.capacity = capacity;
		this.floor = floor;
		this.type = type;
	}

	public String getRoomNumber() {
		return this.room_number;
	}

	public void setRoomNumber(String id) {
		this.room_number = id;
	}

	
	public int getRes_id() {
		return res_id;
	}

	public void setRes_id(int res_id) {
		this.res_id = res_id;
	}

	public int getCapacity() {
		return this.capacity;
	}

	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}

	public int getFloor() {
		return this.floor;
	}

	public void setFloor(int floor) {
		this.floor = floor;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
