package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Students generated by hbm2java
 */
public class Students implements java.io.Serializable {

	private String stdUnityid;
	private Patrons patrons;
	private String stdNumber;
	private String stdCat;
	private String stdClassification;
	private String degreeProgram;
	private int hold;
	private Date dob;
	private String street;
	private String city;
	private int postalCode;
	private int phoneNum;
	private int altPhone;
	private Set<EnrolledCourses> enrolledCourseses = new HashSet<EnrolledCourses>(
			0);

	public Students() {
	}

	public Students(Patrons patrons) {
		this.patrons = patrons;
	}

	public Students(Patrons patrons, String stdNumber, String stdCat,
			String stdClassification, String degreeProgram, int hold,
			Date dob, String street, String city, int postalCode,
			int phoneNum, int altPhone,
			Set<EnrolledCourses> enrolledCourseses) {
		this.patrons = patrons;
		this.stdNumber = stdNumber;
		this.stdCat = stdCat;
		this.stdClassification = stdClassification;
		this.degreeProgram = degreeProgram;
		this.hold = hold;
		this.dob = dob;
		this.street = street;
		this.city = city;
		this.postalCode = postalCode;
		this.phoneNum = phoneNum;
		this.altPhone = altPhone;
		this.enrolledCourseses = enrolledCourseses;
	}

	public String getStdUnityid() {
		return this.stdUnityid;
	}

	public void setStdUnityid(String stdUnityid) {
		this.stdUnityid = stdUnityid;
	}

	public Patrons getPatrons() {
		return this.patrons;
	}

	public void setPatrons(Patrons patrons) {
		this.patrons = patrons;
	}

	public String getStdNumber() {
		return this.stdNumber;
	}

	public void setStdNumber(String stdNumber) {
		this.stdNumber = stdNumber;
	}

	public String getStdCat() {
		return this.stdCat;
	}

	public void setStdCat(String stdCat) {
		this.stdCat = stdCat;
	}

	public String getStdClassification() {
		return this.stdClassification;
	}

	public void setStdClassification(String stdClassification) {
		this.stdClassification = stdClassification;
	}

	public String getDegreeProgram() {
		return this.degreeProgram;
	}

	public void setDegreeProgram(String degreeProgram) {
		this.degreeProgram = degreeProgram;
	}

	public int getHold() {
		return this.hold;
	}

	public void setHold(int hold) {
		this.hold = hold;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public int getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(int postalCode) {
		this.postalCode = postalCode;
	}

	public int getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(int phoneNum) {
		this.phoneNum = phoneNum;
	}

	public int getAltPhone() {
		return this.altPhone;
	}

	public void setAltPhone(int altPhone) {
		this.altPhone = altPhone;
	}

	public Set<EnrolledCourses> getEnrolledCourseses() {
		return this.enrolledCourseses;
	}

	public void setEnrolledCourseses(Set<EnrolledCourses> enrolledCourseses) {
		this.enrolledCourseses = enrolledCourseses;
	}


}
