package edu.ncsu.csc540.model;

// Generated Oct 22, 2015 4:43:38 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Teaches generated by hbm2java
 */
public class Teaches implements java.io.Serializable {

	private BigDecimal cid;
	private Courses courses;
	private Faculty faculty;

	public Teaches() {
	}

	public Teaches(Courses courses, Faculty faculty) {
		this.courses = courses;
		this.faculty = faculty;
	}

	public BigDecimal getCid() {
		return this.cid;
	}

	public void setCid(BigDecimal cid) {
		this.cid = cid;
	}

	public Courses getCourses() {
		return this.courses;
	}

	public void setCourses(Courses courses) {
		this.courses = courses;
	}

	public Faculty getFaculty() {
		return this.faculty;
	}

	public void setFaculty(Faculty faculty) {
		this.faculty = faculty;
	}

}
